### ISSUE TITLE
API has trouble serving trips

### ISSUE THREAD

**Issue by felixrieseberg** [sedouard/connected-car-api#26]
(Don't deal with this before you're back from vacation)

@irjudson fixed Storm and apparently reached a point where he's able to write actual trips to table storage. Since a few things changed around, it seems like the API is now longer able to get those trips, resulting in various `undefined` properties and other errors. I believe that the culprit is in https://github.com/sedouard/connected-car-api/blob/master/lib/table-utils.js#L75-L140, but I'm not sure.
### What's happening

http://connected-car-api.azurewebsites.net/vehicles/55554370439c5a010068293b serves the right data, but http://connected-car-api.azurewebsites.net/vehicles/55554370439c5a010068293b/trips serves this:

``` JSON
{
    "data": [{
        "trip_events": [],
        "links": {
            "self": "http://connected-car-api.azurewebsites.net:80/trips/undefined",
            "driver": {
                "related": "http://connected-car-api.azurewebsites.net:80/drivers/undefined"
            }
        }
    }, {
        "trip_events": [],
        "links": {
            "self": "http://connected-car-api.azurewebsites.net:80/trips/undefined",
            "driver": {
                "related": "http://connected-car-api.azurewebsites.net:80/drivers/undefined"
            }
        }
    }]
}
```

**Comment by sedouard** [comment]
@irjudson - couple issues. first the trip location table data originally for `testcar6` and `testcar8` had partition keys in the form of:
`DEVICE_ID.TRIP_SUMMARY_ROW_KEY`. This is no longer the case therefore in the troubled [area of code](https://github.com/sedouard/connected-car-api/blob/master/lib/table-utils.js#L24-L26) the query is returned wrong.

Second, when you change the name of a table that is used by the api, you must update the `trip_locations_table_name` configuration variable on the azure website, otherwise the trip locations obviously cannot be queried. Before it was `tripLocations` according to the latest data it is `cleanLocations`.

If you can confirm what the table name and the partition key for trip location entries will be, we'll be all set and I can make the fix (which is really easy). This this is really a breaking change in the underlying data source -- please give  a heads up next time.

I'll make the fix on tuesday.

**Comment by irjudson** [comment]
hey Steve. 

the trip locations is indeed on the clean locations table. 

Ivan

**Comment by sedouard** [comment]
couple field name changes too I've noticed such as `MeasurementTime` vs `StartTime`. All easy fixes but again, when we change this stuff they are breaking changes.

**Comment by irjudson** [comment]
Yes, these have all changed, which is what we discussed previously - hence
the API being "draft" until I was done with the backend :)

--Ivan

Ivan R. Judson
irjudson.org
(425) 679-1375

**Comment by sedouard** [comment]
@felixrieseberg please confirm the fix by calling http://connected-car-api-dev.azurewebsites.net/vehicles/55554370439c5a010068293b/trips. This is PR https://github.com/sedouard/connected-car-api/pull/28

I ran Oxidefleet and here's what I see now:

![screen shot 2015-06-22 at 10 44 04 pm](https://cloud.githubusercontent.com/assets/3053263/8299630/1063bbdc-1930-11e5-85da-310f9c15275c.png)

Confirm this is good (I'm not really sure what I'm supposed to see - whether if the locations are supposed to be mapped) and I'll merge it to the live host.

**Comment by felixrieseberg** [comment]
LGTM! I haven't checked, but I also have never seen it work before - so this screenshot alone is already way better than what we have. Thanks!

**Comment by sedouard** [comment]
It worked just like this before I went on vacation lol.

**Comment by sedouard** [comment]
Closed via https://github.com/sedouard/connected-car-api/commit/ea8f793223956c1a35c7e11a2fccd68e269db22b
